import { describe, expect, test } from 'vitest'
import { ipcChannels } from './ipc'

describe('ipcChannels', () => {
  test('has stable channel names', () => {
    expect(ipcChannels.perfGetStartup).toBe('perf:getStartup')
    expect(ipcChannels.jobLog).toBe('job:log')
    expect(ipcChannels.jobStatus).toBe('job:status')
    expect(ipcChannels.jobStart).toBe('job:start')
    expect(ipcChannels.jobCancel).toBe('job:cancel')
    expect(ipcChannels.jobExportLog).toBe('job:exportLog')
    expect(ipcChannels.jobQueueStatus).toBe('job:queueStatus')
    expect(ipcChannels.jobQueueUpdate).toBe('job:queueUpdate')
    expect(ipcChannels.jobHistory).toBe('job:history')
    expect(ipcChannels.jobGetArchivedLog).toBe('job:getArchivedLog')
    expect(ipcChannels.jobListRunArtifacts).toBe('job:listRunArtifacts')
    expect(ipcChannels.jobReadRunFile).toBe('job:readRunFile')
    expect(ipcChannels.logsCleanupPreview).toBe('logs:cleanupPreview')
    expect(ipcChannels.logsCleanup).toBe('logs:cleanup')
    expect(ipcChannels.kbList).toBe('kb:list')
    expect(ipcChannels.kbSave).toBe('kb:save')
    expect(ipcChannels.kbSetDefault).toBe('kb:setDefault')
    expect(ipcChannels.llmGetConfig).toBe('llm:getConfig')
    expect(ipcChannels.llmSetConfig).toBe('llm:setConfig')
    expect(ipcChannels.llmChat).toBe('llm:chat')
    expect(ipcChannels.aggregateSave).toBe('aggregate:save')
    expect(ipcChannels.aggregateList).toBe('aggregate:list')
    expect(ipcChannels.aggregateReadFile).toBe('aggregate:readFile')
    expect(ipcChannels.aggregateDelete).toBe('aggregate:delete')
    expect(ipcChannels.aggregateExport).toBe('aggregate:export')
    expect(ipcChannels.clusterSave).toBe('cluster:save')
    expect(ipcChannels.clusterList).toBe('cluster:list')
    expect(ipcChannels.clusterReadFile).toBe('cluster:readFile')
    expect(ipcChannels.clusterDelete).toBe('cluster:delete')
    expect(ipcChannels.clusterExport).toBe('cluster:export')
    expect(ipcChannels.trayGetConfig).toBe('tray:getConfig')
    expect(ipcChannels.trayUpdateConfig).toBe('tray:updateConfig')
    expect(ipcChannels.appNotify).toBe('app:notify')
    expect(ipcChannels.appGetDbState).toBe('app:getDbState')
    expect(ipcChannels.appUninstall).toBe('app:uninstall')
    expect(ipcChannels.updateCheck).toBe('update:check')
    expect(ipcChannels.updateInstall).toBe('update:install')
    expect(ipcChannels.updateState).toBe('update:state')
    expect(ipcChannels.updateEvent).toBe('update:event')
    expect(ipcChannels.onboardingGet).toBe('onboarding:get')
    expect(ipcChannels.onboardingComplete).toBe('onboarding:complete')
    expect(ipcChannels.onboardingReset).toBe('onboarding:reset')
    expect(ipcChannels.systemCheckPython).toBe('system:checkPython')
    expect(ipcChannels.feedbackCollectBundle).toBe('feedback:collectBundle')
  })
})
