export const ipcChannels = {
  perfGetStartup: 'perf:getStartup',
  jobLog: 'job:log',
  jobStatus: 'job:status',
  jobStart: 'job:start',
  jobCancel: 'job:cancel',
  jobExportLog: 'job:exportLog',
  jobQueueStatus: 'job:queueStatus',
  jobQueueUpdate: 'job:queueUpdate',
  jobHistory: 'job:history',
  jobGetArchivedLog: 'job:getArchivedLog',
  kbList: 'kb:list',
  kbSave: 'kb:save',
  kbSetDefault: 'kb:setDefault',
  trayGetConfig: 'tray:getConfig',
  trayUpdateConfig: 'tray:updateConfig',
  appNotify: 'app:notify',
  appGetDbState: 'app:getDbState',
  updateCheck: 'update:check',
  updateInstall: 'update:install',
  updateState: 'update:state',
  updateEvent: 'update:event',
  onboardingGet: 'onboarding:get',
  onboardingComplete: 'onboarding:complete',
  onboardingReset: 'onboarding:reset',
  systemCheckPython: 'system:checkPython'
} as const
